### ISSUE TITLE
Error: invalid signature trying to install on dsp

### ISSUE THREAD

**Issue by bitcoiners** [liquidapps-io/vgrab#1]
We run a dsp using this repo https://github.com/liquidapps-io/dapp-dsp-k8s-helm, 
when tried to install vram contract on dsp cluster got this error:
```
/dapp-cluster-k8s# zeus unbox vgrab
⚙️Unboxing: vgrab

Error: invalid signature: 0x4f44213c
    at /dapp-cluster-k8s/node_modules/unzip/lib/parse.js:59:13
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

```

**Comment by NatPDeveloper** [comment]
Hello bitcoiners!  Invalid signature errors usually occur when an IPFS package is unavailable.  The vgrab box is available for me in the latest version of zeus.  Please try updating zeus to see if that fixes it:

`npm update -g @liquidapps/zeus-cmd`

**Comment by bitcoiners** [comment]
Thanks. Tried running 
npm update -g @liquidapps/zeus-cmd and it did update zeus to version 1.8.764
but running zeus unbox vgrab after still fails with same error:

```
root@0a4658338d32:/dapp-cluster-k8s# zeus unbox vgrab
⚙️Unboxing: vgrab

Error: invalid signature: 0x4f44213c
    at /dapp-cluster-k8s/node_modules/unzip/lib/parse.js:59:13
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by bitcoiners** [comment]
No change. Still getting same error.

```
dapp-cluster-k8s# zeus --version
1.8.1051
```

I updated mapping.js with

"vgrab": "https://s3.us-east-2.amazonaws.com/liquidapps.artifacts/boxes/e9153cabc53b9c7e19dcce82344209b0c1d1f89470b6edafa1e22ddc33f4387c.zip",

and ran 

zeus unbox vgrab
⚙️Unboxing: vgrab
Error: invalid signature: 0x4f44213c
    at /dapp-cluster-k8s/node_modules/unzip/lib/parse.js:59:13

**Comment by NatPDeveloper** [comment]
Okay, please provide the following information:

- os info: `cat /etc/os-release`
- `npm -v`
- `node -v`
- `nodeos -v`
- `eosio-cpp -v`

This should still only be occuring when an IPFS pointer is dead.  I just went through every supported OS on node v10.15.3 ( recommended version ) and tested the latest eos (1.7.3)/eosio.cdt (1.6.1) versions and I did not get this error.

**Comment by bitcoiners** [comment]
```
on host aws instance

cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"

inside docker
root@164ee965cf99:/dapp-cluster-k8s# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"


root@164ee965cf99:/dapp-cluster-k8s# npm -v
6.4.1


root@164ee965cf99:/dapp-cluster-k8s# nodeos -v
bash: nodeos: command not found


root@164ee965cf99:/dapp-cluster-k8s# eosio-cpp -v
bash: eosio-cpp: command not found

```

**Comment by NatPDeveloper** [comment]
Hm okay.  So I have a few ideas. Docker has been officially deprecated by eosio so there could be additional issues there.  Also, Debian 9 is not officially supported, only Debian 10.  9 is missing libicu60 as a dependency.

If nodeos -v is not found then eos is not installed properly.  The same can be said for eosio-cpp for eosio.cdt.

Can you try running on the AWS instance?  I have Ubuntu 18 setup on my own AWS instance and it works great!

**Comment by bitcoiners** [comment]
I don't know why inside docker it is running Debian 9. I followed instructions from https://github.com/liquidapps-io/dapp-dsp-k8s-helm 
to install dsp on AWS. 
Got to this section:

Test your DSP
Upload a contract that uses vram

**Comment by NatPDeveloper** [comment]
We're deprecating support for k8s.  Many teams preferred to use other methods for setup.

We also have updated docs which I recommend: https://docs.liquidapps.io/en/v1.3/dsps/eosio-node.html.  We provide an example of setting up a DSP in an AWS instance.  You can join the dev Telegram channel as well: https://t.me/joinchat/GTxt3lEL6HLeFzgsWA87qg.

As for Debian 9, we also had to change this on our side in our docker container.  We were using nodejs's default setup which uses Debian 9.  We're now using Ubuntu 18.

Replaced:

```
from node:10
RUN apt-get update \
    && apt-get install -y git apt-transport-https curl libzmq3-dev \
    && rm -rf /var/lib/apt/lists/*
```


With:

```
FROM ubuntu:18.04
RUN echo 'APT::Install-Recommends 0;' >> /etc/apt/apt.conf.d/01norecommends \
  && echo 'APT::Install-Suggests 0;' >> /etc/apt/apt.conf.d/01norecommends \
  && apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y libssl1.0.0 libicu60 awscli lsof golang sudo cmake build-essential wget curl net-tools git make openssl ca-certificates clang-tidy python-pip git xmlstarlet zip unzip gnupg openssl libzmq5-dev rsync libusb-1.0-0 \
  && rm -rf /var/lib/apt/lists/*
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt install nodejs
```

**Comment by bitcoiners** [comment]
Ic. thanks.
So is dsp cluster setup being replaced with a single aws instance?

**Comment by NatPDeveloper** [comment]
My pleasure. Yes single instance.
